export const dataProperties = [
  {
    id: 1,
    location: "BCO. ESPERANZA",
    price: 335,
    price1: 1575,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 2,
    location: "BCO. HUICHAPAN",
    price: 400,
    price1: 2000,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 3,
    location: "BCO. PACHUCA",
    price: 415,
    price1: 2075,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 4,
    location: "BRONCE",
    price: 170,
    price1: 1900,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 5,
    location: "CAFE 2",
    price: 140,
    price1: 640,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 6,
    location: "CAFE 3",
    price: 140,
    price1: 640,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 7,
    location: "CAFE GALINDO",
    price: 170,
    price1: 1900,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 8,
    location: "CHICLE",
    price: 130,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 9,
    location: "CHOCOLATE",
    price: 160,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 10,
    location: "DIAMANTINA",
    price: 350,
    price1: 1750,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 11,
    location: "GRIS DE LOS REME",
    price: 380,
    price1: 1900,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 12,
    location: "GRIS DOTHI",
    price: 130,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 13,
    location: "GRIS ESPERANZA",
    price: 315,
    price1: 1575,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 14,
    location: "GRIS HUICHAPAN",
    price: 400,
    price1: 2000,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 15,
    location: "GRIS QUERETARO",
    price: 350,
    price1: 1750,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 16,
    location: "NARANJA",
    price: 170,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 17,
    location: "NEGRO",
    price: 170,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 18,
    location: "NUEZ",
    price: 160,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 19,
    location: "RECINTO GRIS",
    price: 280,
    price1: 1400,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 20,
    location: "ROJO GAL",
    price: 150,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 21,
    location: "ROJO TAGUI",
    price: 140,
    price1: 1900,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 22,
    location: "ROSA MEXICANO",
    price: 200,
    price1: 3500,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 23,
    location: "CAFE DOTHI",
    price: 2000,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 24,
    location: "CAFE ROJIZO",
    price: 2000,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
   {
    id: 25,
    location: "TABACO",
    price: 2000,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  /*
  {
    id: 6,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 7,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 8,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 9,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 10,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 11,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 12,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 13,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 14,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 15,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 16,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },*/
];
