export const dataProperties = [
  {
    id: 1,
    location: "BCO. ESPERANZA",
    price: 335,
    price1: 1575,
    image: "blanco esperanza.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 2,
    location: "BCO. HUICHAPAN",
    price: 400,
    price1: 2000,
    image: "blanco Huichapan.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 3,
    location: "BCO. PACHUCA",
    price: 415,
    price1: 2075,
    image: "Blanco pachuca.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 4,
    location: "BRONCE",
    price: 170,
    price1: 1900,
    image: "Bronce.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 5,
    location: "CAFE 2",
    price: 140,
    price1: 640,
    image: "cafe 2.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 6,
    location: "CAFE 3",
    price: 140,
    price1: 640,
    image: "cafe 3.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 7,
    location: "CAFE GALINDO",
    price: 170,
    price1: 1900,
    image: "Cafe Galindo.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 8,
    location: "CHICLE",
    price: 130,
    price1: 3300,
    image: "chicle.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 9,
    location: "CHOCOLATE",
    price: 160,
    price1: 3300,
    image: "CHOCOLATE M.JPG",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 10,
    location: "DIAMANTINA",
    price: 350,
    price1: 1750,
    image: "Diamantina.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 11,
    location: "GRIS DE LOS REME",
    price: 380,
    price1: 1900,
    image: "Gris Remedios.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 12,
    location: "GRIS DOTHI",
    price: 130,
    price1: 3300,
    image: "Gris Dothi.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 13,
    location: "GRIS ESPERANZA",
    price: 315,
    price1: 1575,
    image: "gris esperanza.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },/*
  {
   id: 14,
    location: "GRIS HUICHAPAN",
    price: 400,
    price1: 2000,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },*/
  {id: 15,
    location: "GRIS QUERETARO",
    price: 350,
    price1: 1750,
    image: "Gris Queretaro.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 16,
    location: "NARANJA",
    price: 170,
    price1: 3300,
    image: "Naranja.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 17,
    location: "NEGRO",
    price: 170,
    price1: 3300,
    image: "Negro.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 18,
    location: "NUEZ",
    price: 160,
    price1: 3300,
    image: "nuez.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
   id: 19,
    location: "RECINTO GRIS",
    price: 280,
    price1: 1400,
    image: "Recinto.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {id: 20,
    location: "ROJO GAL",
    price: 150,
    price1: 3300,
    image: "Rojo Galindo.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 21,
    location: "ROJO TAGUI",
    price: 140,
    price1: 1900,
    image: "Rojo tagui.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  {
    id: 22,
    location: "ROSA MEXICANO",
    price: 200,
    price1: 3500,
    image: "Rosa.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },/*
  {
    id: 23,
    location: "CAFE DOTHI",
    price: 2000,
    price1: 3300,
    image: "propertie17.jpeg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },*/
  {
    id: 24,
    location: "CAFE ROJIZO",
    price: 2000,
    price1: 3300,
    image: "Rojo Galindo.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
   {
    id: 25,
    location: "TABACO",
    price: 2000,
    price1: 3300,
    image: "Bronce.jpg",
    star: 4.5,
    meters: "Medida",
    meters1: "Lingote",
  },
  
];
